"""add client onboarding table

Revision ID: 831fbbdca909
Revises: e15c709dcf8d
Create Date: 2025-09-25 23:20:21.857781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '831fbbdca909'
down_revision: Union[str, None] = 'e15c709dcf8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_onboarding',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('client_id', sa.BigInteger(), nullable=False),
    sa.Column('answers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('knowledge_level', sa.String(length=20), nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.drop_table('module_fiber_content')
    op.drop_table('learning_modules')
    op.drop_index('idx_fiber_embeddings_local_vector', table_name='fiber_embeddings_local', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_table('fiber_embeddings_local')
    op.drop_table('module_fiber_relationships')
    op.drop_index('idx_chatbot_conversations_created', table_name='chatbot_conversations')
    op.drop_index('idx_chatbot_conversations_session', table_name='chatbot_conversations')
    op.drop_index('idx_chatbot_conversations_user', table_name='chatbot_conversations')
    op.alter_column('content_blocks', 'position',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('content_blocks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.drop_index('idx_content_blocks_subtopic', table_name='content_blocks')
    op.drop_constraint('fiber_applications_fiber_id_application_id_key', 'fiber_applications', type_='unique')
    op.drop_index('idx_fiber_applications_app', table_name='fiber_applications')
    op.drop_index('idx_fiber_applications_fiber', table_name='fiber_applications')
    op.create_index('idx_fiber_application_unique', 'fiber_applications', ['fiber_id', 'application_id'], unique=True)
    op.drop_constraint('fiber_embeddings_fiber_id_content_type_key', 'fiber_embeddings', type_='unique')
    op.drop_index('idx_fiber_embeddings_vector', table_name='fiber_embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_index('idx_fiber_embedding_unique', 'fiber_embeddings', ['fiber_id', 'content_type'], unique=True)
    op.drop_constraint('fiber_properties_fiber_id_property_id_key', 'fiber_properties', type_='unique')
    op.drop_index('idx_fiber_properties_fiber', table_name='fiber_properties')
    op.drop_index('idx_fiber_properties_numeric', table_name='fiber_properties', postgresql_where='(numeric_value IS NOT NULL)')
    op.drop_index('idx_fiber_properties_property', table_name='fiber_properties')
    op.create_index('idx_fiber_property_unique', 'fiber_properties', ['fiber_id', 'property_id'], unique=True)
    op.drop_constraint('fiber_subtypes_class_id_name_key', 'fiber_subtypes', type_='unique')
    op.create_index('idx_fiber_subtypes_unique', 'fiber_subtypes', ['class_id', 'name'], unique=True)
    op.alter_column('fibers', 'structure_image_cms_id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('fibers', 'structure_image_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('idx_fibers_active', table_name='fibers', postgresql_where='(is_active = true)')
    op.drop_index('idx_fibers_applications', table_name='fibers', postgresql_using='gin')
    op.drop_index('idx_fibers_class_subtype', table_name='fibers')
    op.drop_index('idx_fibers_dye_affinity', table_name='fibers', postgresql_using='gin')
    op.drop_index('idx_fibers_functional_groups', table_name='fibers', postgresql_using='gin')
    op.drop_index('idx_fibers_name_lower', table_name='fibers')
    op.drop_index('idx_fibers_name_trgm', table_name='fibers', postgresql_using='gin')
    op.drop_index('idx_fibers_polymer_trgm', table_name='fibers', postgresql_using='gin')
    op.drop_index('idx_fibers_search_vector', table_name='fibers', postgresql_using='gin')
    op.drop_index('idx_fibers_sources', table_name='fibers', postgresql_using='gin')
    op.drop_index('idx_fibers_trade_names', table_name='fibers', postgresql_using='gin')
    op.drop_column('fibers', 'search_vector')
    op.alter_column('modules', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('modules', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('modules', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('modules', 'slug')
    op.alter_column('subtopics', 'difficulty_level',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'basic'::text"))
    op.alter_column('subtopics', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_subtopics_topic', table_name='subtopics')
    op.drop_column('subtopics', 'slug')
    op.alter_column('topics', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_topics_module', table_name='topics')
    op.drop_column('topics', 'slug')
    op.alter_column('user_interactions', 'interaction_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index('idx_user_interactions_created', table_name='user_interactions')
    op.drop_index('idx_user_interactions_session', table_name='user_interactions')
    op.drop_index('idx_user_interactions_type', table_name='user_interactions')
    op.drop_index('idx_user_interactions_user', table_name='user_interactions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_user_interactions_user', 'user_interactions', ['user_id'], unique=False)
    op.create_index('idx_user_interactions_type', 'user_interactions', ['interaction_type'], unique=False)
    op.create_index('idx_user_interactions_session', 'user_interactions', ['session_id'], unique=False)
    op.create_index('idx_user_interactions_created', 'user_interactions', ['created_at'], unique=False)
    op.alter_column('user_interactions', 'interaction_data',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.add_column('topics', sa.Column('slug', sa.TEXT(), sa.Computed("regexp_replace(lower(name), '\\W+'::text, '-'::text, 'g'::text)", persisted=True), autoincrement=False, nullable=True))
    op.create_index('idx_topics_module', 'topics', ['module_id'], unique=False)
    op.alter_column('topics', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('subtopics', sa.Column('slug', sa.TEXT(), sa.Computed("regexp_replace(lower(name), '\\W+'::text, '-'::text, 'g'::text)", persisted=True), autoincrement=False, nullable=True))
    op.create_index('idx_subtopics_topic', 'subtopics', ['topic_id'], unique=False)
    op.alter_column('subtopics', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('subtopics', 'difficulty_level',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'basic'::text"))
    op.add_column('modules', sa.Column('slug', sa.TEXT(), sa.Computed("regexp_replace(lower(name), '\\W+'::text, '-'::text, 'g'::text)", persisted=True), autoincrement=False, nullable=True))
    op.alter_column('modules', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('modules', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('modules', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.add_column('fibers', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('idx_fibers_trade_names', 'fibers', ['trade_names'], unique=False, postgresql_using='gin')
    op.create_index('idx_fibers_sources', 'fibers', ['sources'], unique=False, postgresql_using='gin')
    op.create_index('idx_fibers_search_vector', 'fibers', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('idx_fibers_polymer_trgm', 'fibers', ['polymer_composition'], unique=False, postgresql_using='gin')
    op.create_index('idx_fibers_name_trgm', 'fibers', ['name'], unique=False, postgresql_using='gin')
    op.create_index('idx_fibers_name_lower', 'fibers', [sa.text('lower(name::text)')], unique=False)
    op.create_index('idx_fibers_functional_groups', 'fibers', ['functional_groups'], unique=False, postgresql_using='gin')
    op.create_index('idx_fibers_dye_affinity', 'fibers', ['dye_affinity'], unique=False, postgresql_using='gin')
    op.create_index('idx_fibers_class_subtype', 'fibers', ['class_id', 'subtype_id'], unique=False)
    op.create_index('idx_fibers_applications', 'fibers', ['applications'], unique=False, postgresql_using='gin')
    op.create_index('idx_fibers_active', 'fibers', ['is_active'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('fibers', 'structure_image_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('fibers', 'structure_image_cms_id',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    op.drop_index('idx_fiber_subtypes_unique', table_name='fiber_subtypes')
    op.create_unique_constraint('fiber_subtypes_class_id_name_key', 'fiber_subtypes', ['class_id', 'name'])
    op.drop_index('idx_fiber_property_unique', table_name='fiber_properties')
    op.create_index('idx_fiber_properties_property', 'fiber_properties', ['property_id'], unique=False)
    op.create_index('idx_fiber_properties_numeric', 'fiber_properties', ['property_id', 'numeric_value'], unique=False, postgresql_where='(numeric_value IS NOT NULL)')
    op.create_index('idx_fiber_properties_fiber', 'fiber_properties', ['fiber_id'], unique=False)
    op.create_unique_constraint('fiber_properties_fiber_id_property_id_key', 'fiber_properties', ['fiber_id', 'property_id'])
    op.drop_index('idx_fiber_embedding_unique', table_name='fiber_embeddings')
    op.create_index('idx_fiber_embeddings_vector', 'fiber_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_unique_constraint('fiber_embeddings_fiber_id_content_type_key', 'fiber_embeddings', ['fiber_id', 'content_type'])
    op.drop_index('idx_fiber_application_unique', table_name='fiber_applications')
    op.create_index('idx_fiber_applications_fiber', 'fiber_applications', ['fiber_id'], unique=False)
    op.create_index('idx_fiber_applications_app', 'fiber_applications', ['application_id'], unique=False)
    op.create_unique_constraint('fiber_applications_fiber_id_application_id_key', 'fiber_applications', ['fiber_id', 'application_id'])
    op.create_index('idx_content_blocks_subtopic', 'content_blocks', ['subtopic_id'], unique=False)
    op.alter_column('content_blocks', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True,
               existing_server_default=sa.text("'{}'::jsonb"))
    op.alter_column('content_blocks', 'position',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('idx_chatbot_conversations_user', 'chatbot_conversations', ['user_id'], unique=False)
    op.create_index('idx_chatbot_conversations_session', 'chatbot_conversations', ['session_id'], unique=False)
    op.create_index('idx_chatbot_conversations_created', 'chatbot_conversations', ['created_at'], unique=False)
    op.create_table('module_fiber_relationships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fiber_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('relationship_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('content_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='module_fiber_relationships_pkey')
    )
    op.create_table('fiber_embeddings_local',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fiber_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=384), autoincrement=False, nullable=True),
    sa.Column('embedding_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fiber_id'], ['fibers.id'], name='fiber_embeddings_local_fiber_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='fiber_embeddings_local_pkey'),
    sa.UniqueConstraint('fiber_id', 'content_type', 'embedding_model', name='fiber_embeddings_local_fiber_id_content_type_embedding_mode_key')
    )
    op.create_index('idx_fiber_embeddings_local_vector', 'fiber_embeddings_local', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.create_table('learning_modules',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('learning_modules_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('difficulty_level', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('estimated_duration_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('learning_objectives', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('prerequisites', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('module_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_published', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.CheckConstraint('difficulty_level >= 1 AND difficulty_level <= 5', name='learning_modules_difficulty_level_check'),
    sa.PrimaryKeyConstraint('id', name='learning_modules_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('module_fiber_content',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fiber_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('content_order', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('content_text', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('multimedia_urls', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('interactive_elements', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['fiber_id'], ['fibers.id'], name='module_fiber_content_fiber_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['learning_modules.id'], name='module_fiber_content_module_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='module_fiber_content_pkey'),
    sa.UniqueConstraint('module_id', 'fiber_id', 'content_type', name='module_fiber_content_module_id_fiber_id_content_type_key')
    )
    op.drop_table('client_onboarding')
    # ### end Alembic commands ###
