"""Initial migration

Revision ID: 89f2c9f5d1c0
Revises: 
Create Date: 2025-08-10 21:17:30.222363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89f2c9f5d1c0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('modules',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('study_groups',
    sa.Column('code', sa.CHAR(length=1), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='tags_name_key')
    )
    op.create_table('topics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('module_id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'name', name='topics_module_id_name_key')
    )
    op.create_table('subtopics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('difficulty_level', sa.Text(), server_default=sa.text("'basic'"), nullable=False),
    sa.Column('order_index', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint("difficulty_level in ('intro','basic','intermediate','advanced')", name='subtopics_difficulty_level_check'),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'name', name='subtopics_topic_id_name_key')
    )
    op.create_table('content_blocks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('subtopic_id', sa.BigInteger(), nullable=False),
    sa.Column('block_type', sa.Text(), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.CheckConstraint("block_type in ('text','image','list','quote','table','link','html','code')", name='content_blocks_block_type_check'),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subtopic_id', 'position', name='uq_content_blocks_subtopic_position')
    )
    op.create_table('subtopic_study_groups',
    sa.Column('subtopic_id', sa.BigInteger(), nullable=False),
    sa.Column('group_code', sa.CHAR(length=1), nullable=False),
    sa.ForeignKeyConstraint(['group_code'], ['study_groups.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subtopic_id', 'group_code')
    )
    op.create_table('subtopic_tags',
    sa.Column('subtopic_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['subtopic_id'], ['subtopics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subtopic_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtopic_tags')
    op.drop_table('subtopic_study_groups')
    op.drop_table('content_blocks')
    op.drop_table('subtopics')
    op.drop_table('topics')
    op.drop_table('tags')
    op.drop_table('study_groups')
    op.drop_table('modules')
    # ### end Alembic commands ###
