"""add_is_active_to_special_fibers

Revision ID: f33d388ab02e
Revises: g4j5k6l7m8n9
Create Date: 2025-12-03 23:31:10.313983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f33d388ab02e'
down_revision: Union[str, None] = 'g4j5k6l7m8n9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_verifications_email', table_name='email_verifications')
    op.drop_table('email_verifications')
    op.drop_index('idx_module_embedding_unique', table_name='module_embeddings')
    op.drop_table('module_embeddings')
    op.alter_column('chatbot_conversations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('chatbot_conversations_client_id_fkey', 'chatbot_conversations', type_='foreignkey')
    op.drop_constraint('chatbot_conversations_user_id_fkey', 'chatbot_conversations', type_='foreignkey')
    op.drop_column('chatbot_conversations', 'feedback_text')
    op.drop_column('chatbot_conversations', 'relevant_ids')
    op.drop_column('chatbot_conversations', 'confidence_score')
    op.drop_column('chatbot_conversations', 'feedback_rating')
    op.drop_column('chatbot_conversations', 'context_sources')
    op.drop_column('chatbot_conversations', 'client_type')
    op.drop_column('chatbot_conversations', 'client_id')
    op.alter_column('fibers', 'elastic_modulus_min_gpa',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=8, scale=2),
               comment=None,
               existing_comment='Minimum elastic modulus value in GPa',
               existing_nullable=True)
    op.alter_column('fibers', 'elastic_modulus_max_gpa',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.DECIMAL(precision=8, scale=2),
               comment=None,
               existing_comment='Maximum elastic modulus value in GPa',
               existing_nullable=True)
    op.drop_index('idx_fibers_search_vector', table_name='fibers', postgresql_using='gin')
    op.drop_column('fibers', 'search_vector')
    op.alter_column('knowledge_base_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('knowledge_base_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('knowledge_base_documents', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('knowledge_base_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('knowledge_base_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('knowledge_base_embeddings', 'embedding_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'text-embedding-3-small'::character varying"))
    op.alter_column('knowledge_base_embeddings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_index('idx_kb_embeddings_vector', table_name='knowledge_base_embeddings', postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_constraint('uq_kb_embeddings_doc_chunk', 'knowledge_base_embeddings', type_='unique')
    op.create_index('idx_kb_document_chunk', 'knowledge_base_embeddings', ['document_id', 'chunk_index'], unique=True)
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('quiz_attempts', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('special_fiber_embeddings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('unique_embedding_per_type', 'special_fiber_embeddings', type_='unique')
    op.create_unique_constraint('unique_special_fiber_embedding', 'special_fiber_embeddings', ['special_fiber_id', 'content_type'])
    op.add_column('special_fibers', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('special_fibers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('special_fibers', 'is_active')
    op.alter_column('special_fibers', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.drop_constraint('unique_special_fiber_embedding', 'special_fiber_embeddings', type_='unique')
    op.create_unique_constraint('unique_embedding_per_type', 'special_fiber_embeddings', ['special_fiber_id', 'content_type'])
    op.alter_column('special_fiber_embeddings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('quiz_attempts', 'is_completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_kb_document_chunk', table_name='knowledge_base_embeddings')
    op.create_unique_constraint('uq_kb_embeddings_doc_chunk', 'knowledge_base_embeddings', ['document_id', 'chunk_index'])
    op.create_index('idx_kb_embeddings_vector', 'knowledge_base_embeddings', ['embedding'], unique=False, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.alter_column('knowledge_base_embeddings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('knowledge_base_embeddings', 'embedding_model',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'text-embedding-3-small'::character varying"))
    op.alter_column('knowledge_base_documents', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('knowledge_base_documents', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('knowledge_base_documents', 'is_published',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('knowledge_base_audit_log', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.alter_column('knowledge_base_attachments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
    op.add_column('fibers', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index('idx_fibers_search_vector', 'fibers', ['search_vector'], unique=False, postgresql_using='gin')
    op.alter_column('fibers', 'elastic_modulus_max_gpa',
               existing_type=sa.DECIMAL(precision=8, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               comment='Maximum elastic modulus value in GPa',
               existing_nullable=True)
    op.alter_column('fibers', 'elastic_modulus_min_gpa',
               existing_type=sa.DECIMAL(precision=8, scale=2),
               type_=sa.NUMERIC(precision=10, scale=2),
               comment='Minimum elastic modulus value in GPa',
               existing_nullable=True)
    op.add_column('chatbot_conversations', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chatbot_conversations', sa.Column('client_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('chatbot_conversations', sa.Column('context_sources', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True))
    op.add_column('chatbot_conversations', sa.Column('feedback_rating', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chatbot_conversations', sa.Column('confidence_score', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=True))
    op.add_column('chatbot_conversations', sa.Column('relevant_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('chatbot_conversations', sa.Column('feedback_text', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key('chatbot_conversations_user_id_fkey', 'chatbot_conversations', 'users', ['user_id'], ['id'])
    op.create_foreign_key('chatbot_conversations_client_id_fkey', 'chatbot_conversations', 'clients', ['client_id'], ['id'])
    op.alter_column('chatbot_conversations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('module_embeddings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), autoincrement=False, nullable=True),
    sa.Column('embedding_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='module_embeddings_pkey')
    )
    op.create_index('idx_module_embedding_unique', 'module_embeddings', ['content_type', 'content_id'], unique=True)
    op.create_table('email_verifications',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('verification_code', sa.VARCHAR(length=6), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='email_verifications_pkey')
    )
    op.create_index('ix_email_verifications_email', 'email_verifications', ['email'], unique=False)
    # ### end Alembic commands ###
